services:
  client:
    build: 
      context: ../..
      dockerfile: docker/dev/Dockerfile.client
      target: dev
    ports:
      - "3000:3000"
    networks:
      - lootopia_network
    
  server:
    build: 
      context: ../..
      dockerfile: docker/dev/Dockerfile.server
      target: dev
    ports:
      - "3001:3001"
    networks:
      - lootopia_network

  db:
    image: "postgres:17.2"
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    ports:
      - "5432:5432"
    networks:
      - lootopia_network

networks:
  lootopia_network:
    driver: bridge