apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: client
          image: ghcr.io/william-wtr92/lootopia-client:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: github-regcred
