apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: production
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
