apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3001"
    spec:
      containers:
        - name: server
          image: ghcr.io/william-wtr92/lootopia-server:latest
          ports:
            - containerPort: 3001
      imagePullSecrets:
        - name: github-regcred
