apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3001"
    spec:
      containers:
        - name: server
          image: ghcr.io/william-wtr92/lootopia-server:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3001"
            - name: DB_HOST
              value: "db.production.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db
                  key: database
            - name: REDIS_HOST
              value: "redis.production.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: username
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: password
            - name: REDIS_DB
              value: "0"
            - name: SECURITY_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: server
                  key: jwt-secret
            - name: SECURITY_PASSWORD_PEPPER
              valueFrom:
                secretKeyRef:
                  name: server
                  key: password-pepper
            - name: SECURITY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: server
                  key: cookie-secret
            - name: CORS_ORIGIN
              value: "*"
      imagePullSecrets:
        - name: github-regcred
