apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: production
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
