import type { Config } from "tailwindcss"
import tailwindcssAnimate from "tailwindcss-animate"

export default {
  content: [
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/web/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "rgb(var(--primary) / <alpha-value>)",
        secondary: "var(--secondary)",
        accent: "var(--accent)",
        accentHover: "var(--accent-hover)",
        primaryBg: "var(--primary-bg)",
        secondaryBg: "var(--secondary-bg)",
        error: "rgb(var(--error) / <alpha-value>)",
        success: "rgb(var(--success) / <alpha-value>)",
      },
    },
  },
  safelist: [
    "bg-gradient-to-r",
    "from-amber-400",
    "to-amber-600",
    "from-blue-400",
    "to-blue-600",
    "from-purple-500",
    "to-purple-700",
    "from-emerald-400",
    "to-emerald-600",
    "from-rose-500",
    "to-rose-700",
    "bg-yellow-500",
    "hover:bg-yellow-600",
    "bg-orange-500",
    "hover:bg-orange-600",
    "bg-red-500",
    "hover:bg-red-600",
    "bg-red-700",
    "hover:bg-red-800",
    "bg-blue-500",
    "hover:bg-blue-600",
    "bg-amber-500",
    "hover:bg-amber-600",
    "bg-green-500",
    "hover:bg-green-600",
    "bg-purple-600",
    "hover:bg-purple-700",
    "bg-blue-600",
    "hover:bg-blue-700",
    "bg-green-600",
    "hover:bg-green-700",
    "bg-gray-500",
    "hover:bg-gray-600",
    "bg-success",
    "hover:bg-success/80",
    "bg-error",
    "hover:bg-error/80",
  ],
  plugins: [tailwindcssAnimate],
} satisfies Config
