FROM node:20-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV PNPM_POSTINSTALL_ENABLE=false

RUN corepack enable

WORKDIR /usr/src/app

FROM base AS prod

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages/drizzle ./packages/drizzle

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile --ignore-scripts

WORKDIR /usr/src/app/packages/drizzle

CMD pnpm run db:generate
