apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrations
  namespace: production
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:alpine
          env:
            - name: DB_HOST
              value: "db.production.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db
                  key: username
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL to be ready..."
              until pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER; do
                echo "Waiting for PostgreSQL..."
                sleep 5
              done
              echo "PostgreSQL is ready!"
      containers:
        - name: migrations
          image: ghcr.io/william-wtr92/lootopia-migrations:latest
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "db.production.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db
                  key: database
          command:
            - sh
            - -c
            - |
              echo "Running migrations..."
              pnpm run db:migrate
      restartPolicy: Never
      imagePullSecrets:
        - name: github-regcred
  backoffLimit: 4
