apiVersion: v1
kind: Secret
metadata:
  name: server
  namespace: production
type: Opaque
data:
  jwt-secret: emVmZ29uemVyaXVvZ2ZuYnVpZXpiVUlCRkVaSVVZQkZldWlvemJmaXVoeWV6YmZ2ZTpmZXppb2Z2ZXp1b2liZnZpZXV6eWJm
  password-pepper: emVmZ29uemVyaXVvZ2ZuYnVpZXpiVUlCRkVaSVVZZXpmZ2lrbmV6b2luZkZCZXpmbmVpdWZjbmtkdnN2bg==
  cookie-secret: ZHNsc3osK2V6dmV6dmpleml1dmZlenlpdWJ2ZmV6dm9pZXp2aWV6
